dist: bionic
language: python

python:
  - "3.8"

services:
  - postgresql

env:
  - DJANGO=3.0 DB=p

before_install:
  - psql -c 'create database postgres;' -U postgres

install:
  - pip install -r requirements.txt

script: python manage.py test
