# Generated by Django 3.0.8 on 2020-07-03 18:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('device_type', models.PositiveIntegerField(verbose_name='type')),
                ('status', models.PositiveIntegerField()),
                ('identnr', models.PositiveIntegerField()),
                ('version', models.PositiveIntegerField()),
                ('accessnr', models.PositiveIntegerField()),
                ('manufacturer', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devicies',
                'ordering': ['identnr'],
            },
        ),
        migrations.CreateModel(
            name='DeviceValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('value', models.CharField(max_length=50)),
                ('tariff', models.PositiveIntegerField()),
                ('subunit', models.PositiveIntegerField()),
                ('dimension', models.CharField(max_length=50)),
                ('storagenr', models.PositiveIntegerField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='telemetry.Device')),
            ],
            options={
                'verbose_name': 'Value',
                'verbose_name_plural': 'Values',
            },
        ),
    ]
