# Generated by Django 3.0.8 on 2020-07-04 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0002_auto_20200704_0659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='device_type',
        ),
        migrations.AddField(
            model_name='device',
            name='type',
            field=models.PositiveIntegerField(default=None),
            preserve_default=False,
        ),
    ]
