# Generated by Django 3.0.8 on 2020-07-04 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0003_auto_20200704_0704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='type',
        ),
        migrations.AddField(
            model_name='device',
            name='device_type',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
