# Generated by Django 3.0.8 on 2020-07-05 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0005_auto_20200704_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='identnr',
            field=models.PositiveIntegerField(db_index=True),
        ),
    ]
